### ISSUE TITLE
polyfill.min.js 如何打包进本地文件

### ISSUE THREAD

**Issue by chaohui2** [JowayYoung/bruce-cli#1]
为什么我编译的生产代码中引用了 https://cdn.polyfill.io/v2/polyfill.min.js  这个cdn

这个 js 资源只有 2.3k 但是走了这个cdn后需要1s以上的响应时间,严重影响了首屏加载速度,create-react-app 则未发现此问题.

bruce b 选项如下:
? 请选择构建环境 生产环境
? 请确认是否输出ES6代码 Yes
? 请确认是否动态导入垫片 Yes
? 请确认是否哈希文件名称 Yes
? 请确认是否深度压缩文件 Yes
? 请确认是否时间化根目录 Yes
? 请确认是否分析打包结果 Yes
? 请确认是否上传到服务器 No

**Comment by JowayYoung** [comment]
使用Polyfill服务只是为了减少打包文件的体积，引用此服务会根据浏览器请求的UserAgent返回相关的Polyfill，由于这个服务链接是国外的，所以加载速度会有些慢，后期我会建立一个国内的Polyfill服务，这样使用就会快乐，create-react-app由于没有考虑兼容这个细节问题，所以没有比较的意义。就上述情况来看，建议(请确认是否动态导入垫片)选择No，打包时会根据browserslist和代码中使用到的ES6语法进行添加Polyfill，选择(请确认是否输出ES6代码)为Yes需慎重，因为不会兼容低版本浏览器
