### ISSUE TITLE
bruce b 报错

### ISSUE THREAD

**Issue by zonggg** [JowayYoung/bruce-cli#11]
× Webpack Build
  Compiled with some errors in 2.28s

clean-webpack-plugin: pausing due to webpack errors
Hash: c2322a2f782e38b33d58
Version: webpack 4.44.2
Time: 2280ms
Built at: 2020/11/25 下午3:37:17
        Asset     Size  Chunks  Chunk Names
vendor.dll.js  125 KiB       0  vendor
Entrypoint vendor = vendor.dll.js

ERROR in vendor.dll.js from UglifyJs
undefined

× 动态链接库构建失败

**Comment by JowayYoung** [comment]
有部分代码源码是ES6，用这个配置下[alias](https://github.com/JowayYoung/bruce-cli#%EF%B8%8F%E9%85%8D%E7%BD%AE)
