### ISSUE TITLE
mpa开发环境怎么访问啊？

### ISSUE THREAD

**Issue by sjmlsxp** [JowayYoung/bruce-cli#14]
![image](https://user-images.githubusercontent.com/1901407/101326103-c1613800-38a7-11eb-83c0-d33ac2f4b1e6.png)
提示已经build完成了，但是不会打开浏览器
访问http://127.0.0.1:8080/，直接返回Cannot GET /

请教下，mpa的项目怎么玩啊？

**Comment by JowayYoung** [comment]
MPA项目所有页面放在pages下，假设pages下存在三个文件夹，每个文件夹代表一个页面，这三个文件夹分别是home、list、about，那么访问http://127.0.0.1:8080/home.html，http://127.0.0.1:8080/list.html，http://127.0.0.1:8080/about.html
