### ISSUE TITLE
更新配置后，执行命令会导致全局包丢失

### ISSUE THREAD

**Issue by JuntingLiu** [JowayYoung/bruce-cli#17]
![image](https://user-images.githubusercontent.com/13826695/103496258-8d623e00-4e78-11eb-818b-39811fe863a3.png)

**Comment by JowayYoung** [comment]
更新到最新版本就行，npm un -g bruce-cli，再执行npm i -g bruce-cli

**Comment by JuntingLiu** [comment]
升级到 `bruce-cli@^0.6.2` 正常了。😊

**Comment by JuntingLiu** [comment]
> 更新到最新版本就行，npm un -g bruce-cli，再执行npm i -g bruce-cli

升级到 bruce-cli@^0.6.2 正常了。😊
