### ISSUE TITLE
突然不好使了，报“permission denied”

### ISSUE THREAD

**Issue by sjmlsxp** [JowayYoung/bruce-cli#18]
上午打开vscode，提示Oh My Zsh更新，敲了Y
然后跑bruce b，就出现如下错误：
(node:18651) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, unlink '/usr/local/lib/node_modules/bruce-cli/.gitattributes'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18651) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18651) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

到现在还是一脸懵逼，只能向大神求救了

**Comment by JowayYoung** [comment]
更新到最新版本就行，npm un -g bruce-cli，再执行npm i -g bruce-cli

**Comment by sukai-cheng** [comment]
![image](https://user-images.githubusercontent.com/35868545/104103330-7a1dfb00-52dc-11eb-8c0f-9b0c058f63ae.png)
node的版本为v.14.15.3，安装brucewei ch未成功

**Comment by JowayYoung** [comment]
@sukai-cheng 使用yarn还是npm安装？

**Comment by sukai-cheng** [comment]
yarn 和 npm 都试过，都安装不成功，也许是node的版本太高了，需要降级。😚感觉很麻烦

JowayYoung <notifications@github.com> 于2021年1月11日周一 下午5:08写道：

**Comment by sukai-cheng** [comment]
报错如下：
![Uploading image.png…]()

**Comment by sukai-cheng** [comment]
可以close了，已解决～
