### ISSUE TITLE
能否提供类似 create-react-app eject这样的命令

### ISSUE THREAD

**Issue by chaohui2** [JowayYoung/bruce-cli#2]
npm run eject可以移除项目对react-scripts的依赖,将webpack,Babel等的配置文件导入进项目中,bruce-cli
是否有类似的功能
create-react-app 文档如下:

## `npm run eject`

**Note: this is a one-way operation. Once you `eject`, you can’t go back!**

If you aren’t satisfied with the build tool and configuration choices, you can `eject` at any time. This command will remove the single build dependency from your project.

Instead, it will copy all the configuration files and the transitive dependencies (Webpack, Babel, ESLint, etc) right into your project so you have full control over them. All of the commands except `eject` will still work, but they will point to the copied scripts so you can tweak them. At this point you’re on your own.

You don’t have to ever use `eject`. The curated feature set is suitable for small and middle deployments, and you shouldn’t feel obligated to use this feature. However we understand that this tool wouldn’t be useful if you couldn’t customize it when you are ready for it.

**Comment by JowayYoung** [comment]
好的，谢谢你的建议，后续版本会添加相应功能
