### ISSUE TITLE
bruce安装成功后，输入bruce后会自动删除，出了鬼了，不说了，见下图

### ISSUE THREAD

**Issue by sukai-cheng** [JowayYoung/bruce-cli#20]
npm install之后，运行bruce -v竟然消失了，/usr/local/lib/node_modules/bruce也删除的一干二净
![image](https://user-images.githubusercontent.com/35868545/109608236-86983480-7b64-11eb-96bc-fff90b867169.png)

**Comment by JuntingLiu** [comment]
看下版本号，之前我也遇到过，升级到最新版本就好了。

**Comment by PaulChess** [comment]
> npm版本: 7.6.3  node版本: 14.2.0

今天遇到了同样的问题:
1. 执行`npm install -g bruce-cli`，安装了最新的`0.6.1`版本(看了下npm官方显示的最新版本是`0.6.2`,但是实际装的时候最新只到`0.6.1`)。安装完成后看了下全局的node包，是有`bruce-cli`的。

![image](https://user-images.githubusercontent.com/69644161/112180342-70970480-8c36-11eb-96b3-a7f6729f7660.png)

2. 执行`bruce i`, 等待几秒之后什么都没有出现，命令行进程自动退出。再次执行`bruce i`的时候提示`command not found: bruce`。再看了一下全局node包，发现`bruce-cli`已经被移除了。

**Comment by sukai-cheng** [comment]
@JowayYoung  @JuntingLiu  @PaulChess bruce-cli还在维护中吗？25 days later，实在不行知道弃坑了 ，望周知

**Comment by JowayYoung** [comment]
最近实在太忙，没怎么上github维护，让各位失望了，请大家更新到最新版的bruce-cli，可以解决这个致命的缺陷
