### ISSUE TITLE
多少天了，真的想在倔金上举报你！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！

### ISSUE THREAD

**Issue by sukai-cheng** [JowayYoung/bruce-cli#22]

**Comment by JowayYoung** [comment]
请问是什么问题，有问题可以私聊我啊，这么多地方贴了联系方式

**Comment by sukai-cheng** [comment]
`sudo npm i -g bruce-cli` cpu飙高
![image](https://user-images.githubusercontent.com/35868545/126601492-7178b0b7-cd50-4c4b-92b6-fa321ec2581a.png)

**Comment by sukai-cheng** [comment]
进程貌似已经卡死，我等了差不多10分钟
![image](https://user-images.githubusercontent.com/35868545/126601627-99d09d70-21db-4718-87f7-47fc9c79fd07.png)

**Comment by sukai-cheng** [comment]
日志：
![image](https://user-images.githubusercontent.com/35868545/126601853-ff6fdf9d-ca79-4d41-92b2-c09e3903c238.png)
![image](https://user-images.githubusercontent.com/35868545/126601884-47e289cf-b291-4d54-ad6b-84737d4ff87e.png)
![image](https://user-images.githubusercontent.com/35868545/126602164-b1c2850f-9bd2-4d68-b3f9-3ff77c0a7570.png)
![image](https://user-images.githubusercontent.com/35868545/126602252-5ac57c7b-78aa-48d8-8ef3-6964683d8763.png)

**Comment by sukai-cheng** [comment]
最新版

**Comment by sukai-cheng** [comment]
![image](https://user-images.githubusercontent.com/35868545/126602555-2737a76b-7eea-4c3f-9472-a38402905cad.png)
