### ISSUE TITLE
在init的时候, 安装依赖发生错误

### ISSUE THREAD

**Issue by CJH-1996** [JowayYoung/bruce-cli#4]
![image](https://user-images.githubusercontent.com/55323120/65049192-f0844480-d997-11e9-896c-4a7400f51f0e.png)
报这样的错误 不知道什么问题

**Comment by x1nGoo** [comment]
+1 我init 也遇到了同样的错误
node 版本 10.16.1
npm 版本 6.10.2

**Comment by SQqDd** [comment]
+1+1+1+1+1

**Comment by JowayYoung** [comment]
试一下把node的版本升级到11+

**Comment by JowayYoung** [comment]
有个文件我使用数组的flat()方法，估计没有加垫片，编译过程中没有解析这个API，所以导致出问题，Node升级到11+以上应该就没有问题了
