### ISSUE TITLE
cmd执行bruce b构建项目发生错误直接卡住不动了，什么都不显示，过了几分钟ctrl+c停止。再执行bruce b，报错找不到全局安装的bruce。js

### ISSUE THREAD

**Issue by tieniu1** [JowayYoung/bruce-cli#6]
**执行完bruce b之后，全局安装的bruce被卸载了**

C:\Users\Administrator\Desktop\app>bruce b
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module 'C:\node-v12.16.2-win-x64\node_modules\bruce-cli\bin\bruce.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:862:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)[39m
[90m    at internal/main/run_main_module.js:18:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}

**Comment by JowayYoung** [comment]
没有安装成功，先npm un -g bruce-cli再重新安装
