### ISSUE TITLE
bruce b 显示构建失败

### ISSUE THREAD

**Issue by yucnlee** [JowayYoung/bruce-cli#9]
![issueImg](https://user-images.githubusercontent.com/39013157/96424305-1c25ce00-122d-11eb-9341-fb9d29d6c5b3.jpg)

**Comment by JowayYoung** [comment]
检查下有没有第三方依赖是使用了es5的文件，例如vue-router或swiper，如果有可以在项目的brucerc.js里增加以下配置

module.exports = {
    alias: {
        "vue-router": "vue-router/dist/vue-router.min.js"
    }, // 模块导入快捷方式
}
